[tool.poetry]
name = "settings"
version = "0.1.0"
description = "ğŸ˜ A Mastodon bot for /usr/games/fortune ğŸ˜"
authors = ["Tom Ritchford <tom@swirly.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
lfortune = "^0.3.2"
fortunes-freebsd-classic = "^2021.8.7"
mastodon-py = "^1.8.0"
numpy = "^1.24.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
